<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CompanyEmployee extends Model
{
    use HasFactory;
    protected $fillable = [
        'company_num',
        'num',
        'ArName',
        'EnName',
        'job_date',
        'active',
        'BranchID',
        'jobid',
        'Sliceid',
        'DepartID',
        'PeriodID',
        'GroupID',
        'salary_way',
        'SalaryPeriod',
        'SalaryDays',
        'PaymentMethod',
        'HasAttendance',
        'IsRep',
        'IsPledge',
        'BornDT',
        'Nat',
        'Faculty',
        'sex',
        'ContractState',
        'JobState',
        'mobile1',
        'mobile2',
        'phone',
        'mail',
        'adress',
        'IsFamily',
        'sons',
        'dependents',
        'students',
        'rent',
        'ISTax',
        'ISInsurance',
        'InsurancType',
        'InsurancePreFixValue',
        'InsurancePreChangedValue',
        'InsuranceNum',
        'InsuranceCo',
        'InsuranceWorkFixed',
        'InsuranceWorkChanged',
        'InsuranceCoFixed',
        'InsuranceCoChanged',
        'txt1',
        'txt2',
        'txt3',
        'txt4',
        'txt5',
        'txt6',
        'txt7',
        'txt8',
        'MaxSolfa',
        'raseedkhasm',
        'raseed',
        'Iscredit',
        'SalaryID',
        'CapitalID',
        'CarID',
        'CarNum',
        'CarKind',
        'debit',
        'credit',
        'balance',
        'hisdebit',
        'hiscredit',
        'hisbalance',
        'gasraseed',
        'fixedsale',
        'ISsalePercent',
        'salepercent',
        'timevalue',
        'regnum',
        'ResidencePeriod',
        'Rate',
        'TotalSalary',
        'AbsentRate',
        'TotalDebit',
        'PeriodGroup',
        'TotalPledgeDebit',
        'TotalPledgeCredit',
        'Refusal',
        'Leave',
        'StopSalary',
        'BankAccount',
        'TaskID',
        'holidays',
        'leaves',
        'clients',
        'projects',
        'tasks',
        'assets',
        'timing_sheets',
    ];


    public function companyfinancialfear()
    {
        return $this->hasMany('App\Models\CompanyFinancialYear');
    }
}
